name: Build Deno Executable
run-name: ${{github.actor}} is building Deno Executable
on:
  push:
    branches:
      - main

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno Env
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.28.1
      - name: Compile Linux Executable
        run: deno compile --unstable --allow-read --allow-net --allow-write --target x86_64-unknown-linux-gnu --output bin/x86_linux/twitter-media-download main.ts
      - name: Compile Windows Executable
        run: deno compile --unstable --allow-read --allow-net --allow-write --target x86_64-pc-windows-msvc --output bin/x86_windows/twitter-media-download main.ts
      - name: Compile MacOS x86 Executable
        run: deno compile --unstable --allow-read --allow-net --allow-write --target x86_64-apple-darwin --output bin/x86_darwin/twitter-media-download main.ts
      - name: Compile MacOS ARM Executable
        run: deno compile --unstable --allow-read --allow-net --allow-write --target aarch64-apple-darwin --output bin/amd_darwin/twitter-media-download-macos-arm main.ts
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: twitter-media-download
          path: bin/**/*
      - name: Pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            bin/**/*