name: Publish Deno Executable
run-name: ${{github.actor}} is publishing Deno Executable
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: twitter-media-download