name: Publish Deno Executable
run-name: ${{github.actor}} is publishing Deno Executable
on:
  push:
    branches:
      - main

jobs:
  publish-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno Env
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.28.1
      - name: Compile
        run: deno compile --unstable --allow-read --allow-net --allow-write --output twitter-media-download main.ts
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: twitter-media-download
          path: twitter-media-download
      - name: Tag
        # if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          git tag "v0.1"
          git push origin "v0.1"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: twitter-media-download